name: Reportar Bug
description: Reporte um bug para nos ajudar a melhorar
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## Descreva o bug"
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: Uma descrição clara e objetiva do bug
    validations:
      required: true
  - type: textarea
    id: reproducao
    attributes:
      label: Passos para Reproduzir
      description: Passos para reproduzir o comportamento
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Role para '...'
        4. Veja o erro
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamento Esperado
      description: O que você esperava que acontecesse
    validations:
      required: true
  - type: textarea
    id: captura
    attributes:
      label: Screenshots
      description: Se aplicável, adicione screenshots
  - type: input
    id: navegador
    attributes:
      label: Navegador
      description: Ex: Chrome, Firefox, Edge
  - type: textarea
    id: contexto
    attributes:
      label: Contexto Adicional
      description: Qualquer outra informação relevante
